package org.jetbrains.dukat.ast

enum class AstReflectionType {
    CLASS_DECLARATION,
    DOCUMENT_ROOT,
    EXPRESSION_DECLARATION,
    FUNCTION_DECLARATION,
    FUNCTION_TYPE_DECLARATION,
    INTERFACE_DECLARATION,
    METHOD_DECLARATION,
    PARAM_FUNCTION_DECLARATION,
    PARAM_TYPE_DECLARATION,
    TYPE_DECLARATION,
    TYPE_PARAM,
    UNKNOWN_DECLARATION,
    VARIABLE_DECLARATION
}