package org.jetbrains.dukat.ast

enum class AstReflectionType {
    DOCUMENT_ROOT,
    EXPRESSION_DECLARATION,
    FUNCTION_DECLARATION,
    PARAMETER_DECLARATION,
    TYPE_DECLARATION,
    UNKNOWN_DECLARATION,
    VARIABLE_DECLARATION
}